Repository BreezeChMS/mainsail-ui, pull requests merged in 2021-06, with the labels that each got.

#104 fixes and clarifies some docs [skip chromatic]
  src/components/Dropdown/Dropdown.js
  src/components/PopMenu/PopMenu.stories.js
  src/components/PopMenu/PopMenuItem.stories.js
  src/components/Table/Actions.js
  src/components/Table/Column.js
Labels: documentation, skip-release

#105 Util class improvements
  src/docs/usage/1-css-utilities.stories.mdx
  src/styles/Layout.scss
  src/styles/Text.scss
  src/styles/Utility.scss
Labels: minor, skip-release

#106 Improvements to popmenu
  src/components/ListGroup/ListGroup.js
  src/components/PopMenu/PopMenu.js
  src/components/PopMenu/PopMenu.scss
  src/components/PopMenu/PopMenu.stories.js
  src/components/PopMenu/PopMenu.test.js
  src/components/PopMenu/PopMenuItem.stories.js
Labels: minor, release

#108 Mobile modal
  src/components/Button/Button.js
  src/components/Checkbox/Checkbox.test.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.stories.js
  src/components/Modal/Modal.test.js
  src/styles/Layout.scss
Labels: minor, release

#109 Modal animation fix
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.js
  src/components/FormControl/FormControl.scss
  src/components/Modal/Modal.js
Labels: patch, release

#113 fixes a bug with missing checkbox ref deps
  src/components/Checkbox/Checkbox.js
Labels: patch, release

#114 Fix ally roles
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.stories.js
  src/components/Dropdown/Dropdown.test.js
Labels: patch, release

#115 fixes modal back button getting wrong type to text
  src/components/Modal/Modal.js
Labels: patch, release

#116 patches dropdown css issues
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.js
Labels: patch, release

#117 removes warning
  src/components/FormControl/FormControl.js
Labels: patch, release

#118 adds transition slide up default animation
  src/components/Transition/Transition.js
  src/components/Transition/Transition.scss
  src/components/Transition/Transition.stories.js
Labels: patch, release

#120 Switcher
  src/components/Switcher/Switcher.js
  src/components/Switcher/Switcher.scss
  src/components/Switcher/Switcher.stories.js
  src/components/Switcher/Switcher.test.js
  src/components/Switcher/index.js
  src/components/core/index.js
  src/components/core/index.scss
Labels: minor, skip-release

#119 Add New Icons for the Text Editor
  src/assets/icons/bold.svg
  src/assets/icons/emoji.svg
  src/assets/icons/file.svg
  src/assets/icons/format-options.svg
  src/assets/icons/italic.svg
  src/assets/icons/list-bullets.svg
  src/assets/icons/list-numbers.svg
  src/assets/icons/redo.svg
  src/assets/icons/signature.svg
  src/assets/icons/table.svg
  src/assets/icons/text-align-center.svg
  src/assets/icons/text-align-left.svg
  src/assets/icons/text-align-right.svg
  src/assets/icons/underline.svg
  src/assets/icons/undo.svg
  src/components/Icon/Icon.js
  src/components/Icons/Bold.js
  src/components/Icons/Emoji.js
  src/components/Icons/File.js
  src/components/Icons/FormatOptions.js
  src/components/Icons/Italic.js
  src/components/Icons/ListBullets.js
  src/components/Icons/ListNumbers.js
  src/components/Icons/Redo.js
  src/components/Icons/Signature.js
  src/components/Icons/Table.js
  src/components/Icons/TextAlignCenter.js
  src/components/Icons/TextAlignLeft.js
  src/components/Icons/TextAlignRight.js
  src/components/Icons/Underline.js
  src/components/Icons/Undo.js
  src/components/Icons/index.js
Labels: patch, release

#121 adds missing hook export
  src/components/core/index.js
Labels: patch, release

#122 adds some minor tweaks to switcher
  src/components/Switcher/Switcher.js
  src/components/Switcher/Switcher.stories.js
Labels: patch, release

#123 adds the ability to control overflows more easily
  src/components/Switcher/Switcher.js
  src/components/Switcher/Switcher.scss
  src/styles/Layout.scss
Labels: patch, release

#124 Patching switcher sizing
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.stories.js
  src/components/Switcher/Switcher.js
  src/components/Switcher/Switcher.scss
  src/components/Switcher/Switcher.stories.js
Labels: patch, release

#125 fixes mobile fullscreen breakpoint
  src/components/Modal/Modal.scss
Labels: patch, release

#126 fixes another wrongly used mixin for modal
  src/components/Modal/Modal.scss
Labels: patch, release

#128 adds guide for Transition and Switcher
  src/docs/guides/Animating-mainsail.stories.mdx
Labels: documentation, patch, release

#129 Modal sizing improvements
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.stories.js
  src/utility/responsive.js
Labels: minor, release

#130 improves some docs
  src/docs/guides/Animating-mainsail.stories.mdx
Labels: documentation, skip-release

#131 fixes multiple modal portal wrappers using same id
  src/components/Modal/Modal.js
  src/components/Modal/Modal.stories.js
Labels: patch, release

#133 Modal patches
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.stories.js
  src/styles/Layout.scss
Labels: patch, release

#134 Update docs
  src/components/Modal/Modal.js
  src/components/Modal/Modal.stories.js
Labels: documentation, skip-release

#136 adds multi-modifier support for TimePicker
  src/components/TimePicker/TimePicker.js
  src/components/TimePicker/TimePicker.scss
  src/components/TimePicker/TimePicker.stories.js
Labels: patch, release

#137 adds extra period controls
  src/components/TimePicker/TimePicker.js
  src/components/TimePicker/TimePicker.scss
  src/components/TimePicker/TimePicker.stories.js
  src/components/TimePicker/TimePicker.test.js
Labels: minor, release
